INSERT INTO triviaquestions (topic, question, optionA, optionB, optionC, optionD, correct_option, createdAt, updatedAt)
    ('Politics','American politician and diplomat Madeleine Albright was born in what central European country?','Germany','Poland','Serbia','Czechoslovakia','D',now(),now()),
    ('Politics','At the time of his assassination, what play was Abraham Lincoln watching?','Carmen','Our American Cousin','Uncle Vanya','Mary Stuart','B',NULL,NULL),
    ('Politics','Where was Richard Nixon when he delivered his infamous “I am not a crook” speech?','Portland, Oregon','Washington D.C.','Orlando, Florida','New York, New York','C',NULL,NULL),
    ('Politics','In 1952, Albert Einstein was offered the presidency of which country?','Israel','Germany','England','America','A',NULL,NULL),
    ('Politics','Who was first U.S. president to be impeached?','Andrew Johnson','Donald Trump','Richard Nixon','Bill Clinton','A',NULL,NULL),
    ('Politics','Who became both a vice president and president of the United States without ever being elected to either office?','James Madison','Gerald Ford','Zachary Taylor','Dwight D. Eisenhower','B',NULL,NULL),
    ('Politics','Who was the first female Prime Minister of a European country?','Angela Merkel ','Margaret Thatcher ','Indira Gandhi','Milka Planinc','B',NULL,NULL),
    ('Politics','Which U.S. president issued the Emancipation Proclamation?','James Buchanan','Andrew Johnson','Abraham Lincoln','Theodore Roosevelt','C',NULL,NULL),
    ('Politics','The Bill of Rights contains how many of the first amendments to the United States Constitution?','Eight','Nine','Ten','Eleven','C',NULL,NULL),
    ('Politics','Who was the first U.S. president that was born a citizen of the United States?','George Washington','John Adams','Thomas Jefferson','Martin Van Buren','D',NULL,NULL),
    ('Politics','What political activist organized the famous "March of the Mill Children" from Philadelphia to President Theodore Roosevelt''s summer home in 1903?','Elizabeth Gurley Flynn','Emma Goldman','Helen Keller','Mary Harris Jones','D',NULL,NULL),
    ('Politics','What new economic program did China''s Mao Zedong announce in 1958?','The Great Leap Forward','Trickle-Down Economics','The Worker''s Awakening','The Enlightened Transformation','A',NULL,NULL),
    ('Politics','Who ran for President of the United States with the campaign slogan "A chicken in every pot and a car in every garage"?','Herbert Hoover','William McKinley','Woodrow Wilson','Calvin Coolidge','A',NULL,NULL),
    ('Politics','What U.S. President refused to use the telephone while in office?','Richard Nixon','Calvin Coolidge','Herbert Hoover','Warren G. Harding','B',NULL,NULL),
    ('Politics','Who drafted the U.S. Declaration of Independence?','Abraham Lincoln','Thomas Jefferson','Geroge Washington','King Geroge III','B',NULL,NULL),
    ('Politics','Who wrote the American national anthem?','Francis Drake','F. Scott Fitzgerald','Francis Scott Key','Francis Bellamy','C',NULL,NULL),
    ('Politics','What is the nickname for the old regulations requiring racial segregation?','Old Crow laws','Stone the Crows laws','Jim Crow laws','Blue laws','C',NULL,NULL),
    ('Politics','Which document does the Fourth of July commemorate?','Gettysburg Address','Articles of Confederation','Constitution','Declaration of Independence','D',NULL,NULL),
    ('Politics','What kind of government does the United States have?','Democracy','Monarchy','Gerontocracy','Republic','D',NULL,NULL),
    ('Politics','How many members are in the U.S. Senate?','100','50','150','200','A',NULL,NULL),
    ('Politics','In the case of a tied vote in the U.S. Senate, the deciding vote is cast by…','the vice president','the president','the Senate majority leader','the Senate parliamentarian','A',NULL,NULL),
    ('Politics','How many U.S. presidents have been assassinated?','One','Four','Two','Three','B',NULL,NULL),
    ('Politics','How many Supreme Court justices are there?','Eight','Nine','Eleven','Twelve','B',NULL,NULL),
    ('Politics','What is the only Constitutional amendment to repeal another amendment?','11th Amendment','19th Amendment','21st Amendment','25th Amendment','C',NULL,NULL),
    ('Politics','When did Sirimavo Bandaranaike become as world’s first female Prime Minister?','1920','1950','1960','1970','C',NULL,NULL),
    ('Sports','Which NBA player is represented in the NBA logo','Jerry West','kobe bryant','Shaq','Karl Malone','A',NULL,NULL),
    ('Sports','What year was Tom Brady drafted?','1999','2005','1980','2000','D',NULL,NULL),
    ('Sports','When did Michael Jordan win his first NBA championship ','1995','1991','1996','1989','B',NULL,NULL),
    ('Sports','Which US city won the MLS cup in 2015 ','Dallas','Seattle ','New York','Portland','D',NULL,NULL),
    ('Sports','What age did Tiger woods turn pro?','16','25','20','21','B',NULL,NULL),
    ('Sports','When was the last time Seattle Seahawks wond Superbowl?','2014','1999','2017','2005','A',NULL,NULL),
    ('Sports','Which US state has the most MLB teams?','New York','Texas','California ','Florida ','C',NULL,NULL),
    ('Sports','When was the first year of the Women''s tennis US Open?','1887','1929','1985','1954','A',NULL,NULL),
    ('Sports','Which country held the summer Olympics in 2016','Russia','China','Brazil','United States','C',NULL,NULL),
    ('Sports','How many fouls can you give before you are fouled out in the NBA?','5','6','4','7','B',NULL,NULL),
    ('Sports','What is the minimum amount of players on a professional Hockey team?','15','12','25','20','D',NULL,NULL),
    ('Sports','How many football teams are in the National Footbal League?','30','24','32','40','C',NULL,NULL),
    ('Sports','How many teams are in the Women''s National Basketball Association?','24','12','20','28','B',NULL,NULL),
    ('Sports','How many points is a touchdown in the NFL?','6','7','8','3','A',NULL,NULL),
    ('Sports','Which olympic athlete owns the 100 meter world record?','Justin Gattlin','Ben Johnson','Usain Bolt','Carl Lewis','C',NULL,NULL),
    ('Sports','Which Olmpian holds the most medals in indivudal events?','Michael Jordan','Michael Phelps','Usain Bolt','Larisa Latynina','B',NULL,NULL),
    ('Sports','Which Country will host the 2020 Olympics (rescuedled to 2021)?','China','Russia ','Germany ','Japan','D',NULL,NULL),
    ('Sports','Which sport is refered to commonly as "America''s Pastime"? ','Baseball','football','Soccer ','Basketball','A',NULL,NULL),
    ('Sports','Which professional boxer has never lost a professional fight?','Muhammad Ali','Floyd Mayweather Jr','Mike Tyson','Roy Jones Jr','B',NULL,NULL),
    ('Sports','How many total rounds are in UFC main event?','5','4','3','10','A',NULL,NULL),
    ('Sports','How many rounds are in a professional game of golf?','17','12','18','9','C',NULL,NULL),
    ('Sports','Who was the first African American baseball player to play in the MLB','Hank Aaron','Willie Mays','Ken Griffey ','Jackie Robinson','D',NULL,NULL),
    ('Sports','How many career home runs does Ken Griffey Jr have?','700','600','630','720','C',NULL,NULL),
    ('Sports','Which NBA player on this list score 81 points in one game?','David Robinson ','Michael Jordan','Kobe Bryant','Lebron James','C',NULL,NULL),
    ('Sports','Which professional sport was founded first ','NHL','NFL','NBA','MLS','A',NULL,NULL),
    ('TV','How many seasons of friends are there?','5','6','9','10','D',NULL,NULL),
    ('TV','Who is the host of America''s Next top Model?','Paris Hilton','Tyra Banks','RuPaul','Heidi Klum','B',NULL,NULL),
    ('TV','The show "Insecure" is based on works in what other entertainment medium?','Drawing','Music','Webseries','Tweets','C',NULL,NULL),
    ('TV','What is the name of the college on "Dear White People"?','Winchester College','Arial College','Barden University','Harvard','A',NULL,NULL),
    ('TV','What cop show does Andy Samberg star in?','Chicago PD','Law and Order','Brooklyn Nine-Nine','Criminal Minds','C',NULL,NULL),
    ('TV','The TV show "Game of Thrones" is based on a novel by which author?','George R. R. Miller','Arthur Miller','Ian Fleming','Thomas Harding','A',NULL,NULL),
    ('TV','What is the name of the basketball team on the show "One Tree Hill"?','The Eagles','The Ravens','The Raiders','The Phantoms','B',NULL,NULL),
    ('TV','Ted Mosby and Marshall Eriksen are both characters on which show?','How I Met Your Mother','One Tree Hill','Community','Lie To Me','A',NULL,NULL),
    ('TV','On the show "Victorious", what is Tori''s talent?','Violin ','Guitar','Dancing ','Singing','D',NULL,NULL),
    ('TV','What show starts Courtney Cox?','Once Upon a Time','Glee','Cougar Town','Castle','C',NULL,NULL),
    ('TV','In which city do Ross and Rachel Get married in?','Los Angeles','Paris','Las Vegas','New York City','C',NULL,NULL),
    ('TV','In the second season of HBO series "Game of Thrones", to whom did Brienne swear an oath of fealty?','Sansa Stark','Catelyn Stark','Ned Stark','Jamie Lanister','B',NULL,NULL),
    ('TV','What is Rick''s last name in "Rick and Morty"?','Sanchez','Smith','Lopez','Johnson','A',NULL,NULL),
    ('TV','What beloved anti-hero becomes a meth cook in order to support his family?','Tony Soprano','Walter White','Vic Mackey','Jimmy Mcnulty','B',NULL,NULL),
    ('TV','Who killed Keith Scott?','Nathan','Brooke','Dan','Peyton','C',NULL,NULL),
    ('TV','In Monica from Friends Apartment, what is the color of Ottoman?','Green','Purple','Red','Blue','A',NULL,NULL),
    ('TV','Who has won the most Halloween Heists in Brooklyn Nine-Nine?','Holt','Jake','Amy','Gina','A',NULL,NULL),
    ('TV','Which Season of Friends is the only one without a Thanksgiving Episode?','3','4','5','2','D',NULL,NULL),
    ('TV','What is the real name of the Pontiac Bandit?','Derek Judd','Judy Jones','Doug Judy','Doug Jones','C',NULL,NULL),
    ('TV','Which one of these is not a Tanner sister?','Michelle','Kimmy','DJ','Stephanie','B',NULL,NULL),
    ('TV','What year did Game of Thrones premiere? ','2011','2012','2010','2009','A',NULL,NULL),
    ('TV','Who did Uncle Jessie marry?','Stacy','Kimmy','Sara','Becky','D',NULL,NULL),
    ('TV','What is Catelyn Stark''s maiden name?','Tyrell','Martell','Tully','Greyjoy','C',NULL,NULL),
    ('TV','Whats the name of the Tanners'' dog?','Rex','Ryder','Comet','Carl','C',NULL,NULL),
    ('TV','Who has seven brothers in Brooklyn Nine-Nine?','Rosa','Amy','Charles','Gina','B',NULL,NULL),
    ('Around the World','Which Country has the longest coastline in the world?','USA','Brazil','Morocco','Canada','D',NULL,NULL),
    ('Around the World','Which country holds the world''s largest population?','India','Iran','China','Mexico','C ',NULL,NULL),
    ('Around the World','What is the most popular language spoken in Sudan?','Arabic','Fulani','Swahili','Amharic','A',NULL,NULL),
    ('Around the World','Which country does the cultural dance Dabke originate from?','Iran','Palestine','Portugal','Nigeria','B',NULL,NULL),
    ('Around the World','After the Nile, what is the longest river in the world?','Amazon','Mississippi','Yangtze','Colombia','A',NULL,NULL),
    ('Around the World','In which country is it a taboo to write someone’s name in red?','Turkey','South Korea','Thailand','Chile','B',NULL,NULL),
    ('Around the World','In which Chinese ethnic group do brides cry for a month as a wedding preparation?','Fuji','Uyghur','Tujia','Tibetan','A',NULL,NULL),
    ('Around the World','How many languages are spoken in Kenya?','42','30','12','68','D',NULL,NULL),
    ('Around the World','Which country has a ban on religion?','Tajikistan','Pakistan','Iraq','South Africa','A',NULL,NULL),
    ('Around the World','Which country has a ban on chewing gum?','Saudi Arabia','Haiti','Peru','Singapore','D',NULL,NULL),
    ('Around the World','Which country follows a calendar that is 7 years behind?','Haiti','Jamaica','Ethiopia','Niger','C',NULL,NULL),
    ('Around the World','In which country is it unacceptable to clink glasses?','Hungary','Norway','Germany','Netherlands','A',NULL,NULL),
    ('Around the World','Out of 2.43 billion acres of land, how much is reserved for Native Americans in the United States?','0.5 Billion','56 Million','20 Million','115 Million','D',NULL,NULL),
    ('Around the World','Which tribe is known for having the tallest men in the world?','Dinka of South Sudan','Ja''ali of North Sudan','Hawiye of Somalia','Isaaq of Somalia','A',NULL,NULL),
    ('Around the World','Which religion is known as the world’s oldest?','Judaism','Paganism','Hinduism','Islam','C',NULL,NULL),
    ('Around the World','Which East Asian ethnic group members practice fraternal polyandry?','Tujia','Tibetans','Miao','Han','B',NULL,NULL),
    ('Around the World','Which country was the first to implement a ban on thin plastic bags?','Singapore','Papa New Guinea','Ethiopia','Bangladesh','D',NULL,NULL),
    ('Around the World','How many native tribes are there in Alaska today?','231','432','47','108','A',NULL,NULL),
    ('Around the World','How many countries are recognized by the UN?','205','195','196','187','B',NULL,NULL),
    ('Around the World','Which country has a two-child policy?','China','Japan','North Korea','Thailand','A',NULL,NULL);
